const REPORTS = [
  {
    id: "natal",
    page: "dogum-haritasi-analizi.html",
    title: "Haritanı Tanı Raporu",
    short: "Doğum haritanı bütüncül ele alan, ilişkiler, kariyer ve yeteneklerine dair 20+ sayfalık kapsamlı analiz.",
    price: 500,
    needsTwoPeople: false,
  },
  {
    id: "cocuk",
    page: "cocugunu-tani-analizi.html",
    title: "Çocuğunu Tanı Raporu",
    short: "Çocuğun doğum haritasını yaşına göre yorumlayan; öğrenme stilini, güçlü yanlarını, duygusal ihtiyaçlarını, sosyal gelişimini ve yeteneklerini ele alan, sonunda ebeveyne özel uygulama rehberi sunan 14+ sayfalık gelişim ve eğitim raporu.",
    price: 500,
    needsTwoPeople: false,
  },
  {
    id: "solar_return",
    title: "Solar Return Raporu",
    short: "Güneş'in natal pozisyonuna döndüğü an için çıkarılan, kişisel yeni yılını temsil eden 14+ sayfalık rapor.",
    price: 250,
    needsTwoPeople: false,
  },
  {
    id: "lunar_return",
    title: "Lunar Return Raporu",
    short: "Ay'ın natal pozisyonuna döndüğü an için çıkarılan, aylık duygusal döngünü anlatan 12+ sayfalık rapor.",
    price: 150,
    needsTwoPeople: false,
  },
  {
    id: "sinastri",
    page: "sinastri-uyum-analizi.html",
    title: "Sinastri Raporu",
    short: "İki kişinin doğum haritaları arasındaki etkileşimi analiz eden 18+ sayfalık ilişki uyum raporu.",
    price: 500,
    needsTwoPeople: true,
  },
  {
    id: "matrix",
    page: "kader-matrisi-analizi.html",
    title: "Kader Matrisi Raporu",
    short: "Doğum tarihinden hesaplanan 22 Arkana (Ladini yöntemi) oktagramıyla karakterini; karmik kuyruğunu, aşk, para ve yetenek hat kombinasyonlarını, çakralarını, yaşam blokajlarını ve yaş dönemlerini tek tek çözen 24+ sayfalık numeroloji raporu.",
    price: 400,
    needsTwoPeople: false,
  },
  {
    id: "matrix_uyum",
    title: "Kader Matrisi Uyum Raporu",
    short: "İki kişinin oktagramlarının birleşiminden doğan ortak enerjileri; her iki tarafın hat kombinasyonlarını, bağlanma dinamiklerini, ilişki–para–karmik bağ blokajlarını ve ilişkinin karmik misyonunu derinlemesine analiz eden 30+ sayfalık uyum raporu.",
    price: 500,
    needsTwoPeople: true,
  },
  {
    id: "transit",
    title: "Transit Raporu",
    short: "Ev geçişleri, açılar ve ev yöneticilikleriyle önümüzdeki 12 ayı tarih tarih yorumlayan 11+ sayfalık öngörü raporu.",
    price: 300,
    needsTwoPeople: false,
  },
  {
    id: "horary",
    title: "Soru Astrolojisi (Horary) Raporu",
    short: "Aklındaki tek bir somut soruya, tam o soruyu sorduğun anın gökyüzünden yanıt arayan kadim bir yöntem. Doğum bilgisi gerekmez — yalnızca net bir soru yeterli. Kayıp bir eşyanın yeri, bir işin olup olmayacağı, iki seçenek arasındaki tercih ya da bir konunun nasıl gelişeceği gibi merak ettiğini; kişiye özel, akıcı ve dürüst bir okumayla yanıtlayan 3-4 sayfalık soru raporu. Kesin kehanet değildir; gökyüzü net konuşmadığında bunu da dürüstçe söyleriz.",
    price: 450,
    needsTwoPeople: false,
  },
];
