const REPORTS = [
  {
    id: "natal",
    title: "Haritanı Tanı Raporu",
    short: "Doğum haritanı bütüncül ele alan, ilişkiler, kariyer ve yeteneklerine dair 18+ sayfalık kapsamlı analiz.",
    price: 500,
    needsTwoPeople: false,
  },
  {
    id: "solar_return",
    title: "Solar Return Raporu",
    short: "Güneş'in natal pozisyonuna döndüğü an için çıkarılan, kişisel yeni yılını temsil eden 14+ sayfalık rapor.",
    price: 250,
    needsTwoPeople: false,
  },
  {
    id: "lunar_return",
    title: "Lunar Return Raporu",
    short: "Ay'ın natal pozisyonuna döndüğü an için çıkarılan, aylık duygusal döngünü anlatan 12+ sayfalık rapor.",
    price: 150,
    needsTwoPeople: false,
  },
  {
    id: "sinastri",
    title: "Sinastri Raporu",
    short: "İki kişinin doğum haritaları arasındaki etkileşimi analiz eden 18+ sayfalık ilişki uyum raporu.",
    price: 500,
    needsTwoPeople: true,
  },
  {
    id: "matrix",
    title: "Kader Matrisi Raporu",
    short: "Doğum tarihinden hesaplanan 22 arkan sistemiyle karakterini, karmik yükünü, para ve ilişki kapılarını çözen 11+ sayfalık numeroloji raporu.",
    price: 400,
    needsTwoPeople: false,
  },
  {
    id: "matrix_uyum",
    title: "Kader Matrisi Uyum Raporu",
    short: "İki kişinin enerjilerinin birleşiminden doğan ortak arketipleri ve ilişkinin karmik misyonunu analiz eden 11+ sayfalık uyum raporu.",
    price: 500,
    needsTwoPeople: true,
  },
  {
    id: "transit",
    title: "Transit Raporu",
    short: "Önümüzdeki 12 ay için gökyüzünün natal haritanla kurduğu temasları tarih tarih yorumlayan 11+ sayfalık öngörü raporu.",
    price: 300,
    needsTwoPeople: false,
  },
];
